services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "127.0.0.1:8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./certs:/mosquitto/certs:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  dnsmasq:
    image: 4km3/dnsmasq:latest
    container_name: dnsmasq
    restart: unless-stopped
    ports:
      - "5380:53/udp"
      - "5380:53/tcp"
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
    cap_add:
      - NET_ADMIN

volumes:
  mosquitto-data:
  mosquitto-log:


